server:
  port: 9999
security:
  formlogin: false
  user:
    password: user
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: openid
      auto-approve-scopes: '.*'
#zuul:
#  routes:
#    resource:
#      path: /resource/**
#      url: http://localhost:9000
#      sensitive-headers: